project_id = "mcnntxmpaucquanimhhq"

[api]
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
major_version = 15

[studio]
port = 54323
api_url = "http://localhost:54321"

[inbucket]
port = 54324

[storage]
file_size_limit = "50MiB"
image_transformation = {enabled = true}

[auth]
site_url = "http://localhost:8080"
additional_redirect_urls = ["https://localhost:8080", "https://mcnntxmpaucquanimhhq.lovableproject.com"]
jwt_expiry = 3600
enable_signup = true
enable_confirmations = false
password_min_length = 6
enable_anonymous_sign_ins = false

[auth.email]
enable_signup = true
double_confirm_changes = false
enable_confirmations = false
secure_email_change_enabled = false

[auth.security]
captcha_enabled = false
password_strength_enabled = false

[edge_functions]
[functions.send-confirmation-email]
verify_jwt = false