// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sreiqcgutrnhtgdutprl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNyZWlxY2d1dHJuaHRnZHV0cHJsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3MzM3ODAsImV4cCI6MjA3MDMwOTc4MH0.9oV6RasL-4rdZzIxCFI7i6eiHjXXdMn1NDP6slZ-d9I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});